// Real GSX retailer directory, parsed from the QuickBooks customer export
// "GSX Customers 090826.xlsx" (see the completion report delivered with this
// file for the full parsing/naming methodology). Sanity has a full
// `dispensary` schema (sanity/schemas/dispensary.ts) but zero documents
// exist in the dataset yet — this file is the real retailer list until
// those documents are authored there; lib/retailers/getRetailers.ts uses
// Sanity first and falls back to this array, so nothing else needs to
// change when that happens.
//
// Coordinates are ZIP-centroid (via the `zipcodes` package — the same
// dataset already used for the visitor's own ZIP in lib/geo/zipLookup.ts),
// not precise per-address geocoding. See the completion report for why
// this is the recommended approach rather than a new geocoding step.
//
// 3 retailers from the source spreadsheet are deliberately not included
// here (2 with no address on file, 1 whose ZIP isn't in the geocoding
// dataset) — flagged in the completion report rather than guessed. A
// handful of entries carry a `notes` field recording the original
// QuickBooks customer name where the public display name differs from it
// (storefront/trade name preferred over a legal entity name, per instruction).

import type { Retailer } from './types'

export const RETAILERS: Retailer[] = [
  {
    id: 'gsx-18',
    slug: 'bodega-ada-oklahoma-kush-cannabis',
    name: "Bodega Ada - Oklahoma Kush Cannabis",
    address: "1006 N. Mississippi Ave",
    city: "Ada",
    state: 'OK',
    zip: '74820',
    lat: 34.78,
    lng: -96.6924,
    active: true,
  },
  {
    id: 'gsx-43',
    slug: 'dispensary-near-me-arcadia',
    name: "Dispensary Near Me (Arcadia)",
    address: "9551 E. Waterloo Rd.",
    city: "Arcadia",
    state: 'OK',
    zip: '73007',
    lat: 35.6543,
    lng: -97.3243,
    active: true,
  },
  {
    id: 'gsx-19',
    slug: 'bodega-ardmore-a-whpmd',
    name: "Bodega Ardmore - A&WHPMD",
    address: "816 12th Ave NW",
    city: "Ardmore",
    state: 'OK',
    zip: '73401',
    lat: 34.1566,
    lng: -97.1792,
    active: true,
  },
  {
    id: 'gsx-15',
    slug: 'arkoma-cannabis-company-llc',
    name: "Arkoma Cannabis Company LLC",
    address: "525 Main St",
    city: "Arkoma",
    state: 'OK',
    zip: '74901',
    lat: 35.3434,
    lng: -94.4403,
    active: true,
  },
  {
    id: 'gsx-72',
    slug: 'humboldt-cannabis-bartlesville',
    name: "Humboldt Cannabis - Bartlesville",
    notes: "QuickBooks legal/source name: Humboldt Cannabis - Bartlesville. Same address also billed under a second customer record (\"Martan LLC (Humboldt Bartlesville)\") — merged to one listing.",
    address: "214 SE Frank Phillips Blvd",
    city: "Bartlesville",
    state: 'OK',
    zip: '74003',
    lat: 36.744,
    lng: -95.9921,
    active: true,
  },
  {
    id: 'gsx-140',
    slug: 'toke-and-grow-bartlesville',
    name: "Toke and Grow - Bartlesville",
    address: "1317 SW Frank Phillips Blvd",
    city: "Bartlesville",
    state: 'OK',
    zip: '74003',
    lat: 36.744,
    lng: -95.9921,
    active: true,
  },
  {
    id: 'gsx-44',
    slug: 'trich-home',
    name: "Trich Home",
    notes: "QuickBooks legal/source name: Doc's Craft Cannabis (Trich Home)",
    address: "128 NE Washington Blvd",
    city: "Bartlesville",
    state: 'OK',
    zip: '74006',
    lat: 36.7366,
    lng: -95.9251,
    active: true,
  },
  {
    id: 'gsx-85',
    slug: 'kotton-mouth-dispensary',
    name: "Kotton Mouth Dispensary",
    address: "7425 NW 23rd St.",
    city: "Bethany",
    state: 'OK',
    zip: '73008',
    lat: 35.5043,
    lng: -97.6399,
    active: true,
  },
  {
    id: 'gsx-45',
    slug: 'doctor-green-bixby-llc',
    name: "Doctor Green Bixby LLC",
    address: "14657 S. Memorial Drive",
    city: "Bixby",
    state: 'OK',
    zip: '74008',
    lat: 35.942,
    lng: -95.8833,
    active: true,
  },
  {
    id: 'gsx-71',
    slug: 'the-green-gremlin',
    name: "The Green Gremlin",
    notes: "QuickBooks legal/source name: Humboldt Bixby (The Green Gremlin)",
    address: "13406 S. Memorial Dr",
    city: "Bixby",
    state: 'OK',
    zip: '74008',
    lat: 35.942,
    lng: -95.8833,
    active: true,
  },
  {
    id: 'gsx-137',
    slug: 'white-barn',
    name: "White Barn",
    notes: "QuickBooks legal/source name: The Bakery Cannabis Disp. (White Barn)",
    address: "13161 S. Memorial Drive",
    city: "Bixby",
    state: 'OK',
    zip: '74008',
    lat: 35.942,
    lng: -95.8833,
    active: true,
  },
  {
    id: 'gsx-9',
    slug: '420-7-bristow',
    name: "420/7 Bristow",
    address: "105 S. Main Street",
    city: "Bristow",
    state: 'OK',
    zip: '74010',
    lat: 35.8209,
    lng: -96.3758,
    active: true,
  },
  {
    id: 'gsx-92',
    slug: 'mid-west-grass-station-llc',
    name: "Mid-West Grass Station LLC",
    address: "301 E. 1st Ave",
    city: "Bristow",
    state: 'OK',
    zip: '74010',
    lat: 35.8209,
    lng: -96.3758,
    active: true,
  },
  {
    id: 'gsx-8',
    slug: 'cowboy-kush',
    name: "Cowboy Kush",
    notes: "QuickBooks legal/source name: 420 Holistic Dispensary LLC (Cowboy Kush)",
    address: "514 N. Elm Pl",
    city: "Broken Arrow",
    state: 'OK',
    zip: '74012',
    lat: 36.0447,
    lng: -95.8079,
    active: true,
  },
  {
    id: 'gsx-157',
    slug: 'green-hub',
    name: "Green Hub",
    notes: "QuickBooks legal/source name: Z&M Inc (Green Hub)",
    address: "6122 S. Garnett Road Suite C",
    city: "Broken Arrow",
    state: 'OK',
    zip: '74012',
    lat: 36.0447,
    lng: -95.8079,
    active: true,
  },
  {
    id: 'gsx-3',
    slug: 'hamilton-s-ba',
    name: "Hamilton's BA",
    notes: "QuickBooks legal/source name: 318 Inc (Hamilton's BA)",
    address: "1350 E. Kenosha St",
    city: "Broken Arrow",
    state: 'OK',
    zip: '74012',
    lat: 36.0447,
    lng: -95.8079,
    active: true,
  },
  {
    id: 'gsx-70',
    slug: 'house-of-cannabis-ok',
    name: "House of Cannabis OK",
    address: "6503 S. Elm Place",
    city: "Broken Arrow",
    state: 'OK',
    zip: '74011',
    lat: 35.9908,
    lng: -95.8143,
    active: true,
  },
  {
    id: 'gsx-4',
    slug: 'limee',
    name: "Limee",
    notes: "QuickBooks legal/source name: 4-C's Shop (Limee)",
    address: "25695 E. 71st St S.",
    city: "Broken Arrow",
    state: 'OK',
    zip: '74014',
    lat: 36.0544,
    lng: -95.7223,
    active: true,
  },
  {
    id: 'gsx-91',
    slug: 'med-pharm-inc',
    name: "Med Pharm Inc",
    address: "24683 E. Highway 51",
    city: "Broken Arrow",
    state: 'OK',
    zip: '74014',
    lat: 36.0544,
    lng: -95.7223,
    active: true,
  },
  {
    id: 'gsx-147',
    slug: 'tulsa-tree-house-inc',
    name: "Tulsa Tree House Inc",
    address: "7842 S. Elm Place",
    city: "Broken Arrow",
    state: 'OK',
    zip: '74011',
    lat: 35.9908,
    lng: -95.8143,
    active: true,
  },
  {
    id: 'gsx-2',
    slug: 'house-of-dank-catoosa',
    name: "House of Dank Catoosa",
    notes: "QuickBooks legal/source name: 24K Medical LLC (House of Dank Catoosa)",
    address: "750 S. Cherokee St",
    city: "Catoosa",
    state: 'OK',
    zip: '74015',
    lat: 36.1721,
    lng: -95.7273,
    active: true,
  },
  {
    id: 'gsx-114',
    slug: 'phaded-dreams-llc',
    name: "Phaded Dreams LLC",
    address: "2400 N. Highway 66",
    city: "Catoosa",
    state: 'OK',
    zip: '74015',
    lat: 36.1721,
    lng: -95.7273,
    active: true,
  },
  {
    id: 'gsx-38',
    slug: 'dazey-s-checotah',
    name: "Dazey's - Checotah",
    address: "107 NW 7th St.",
    city: "Checotah",
    state: 'OK',
    zip: '74426',
    lat: 35.4358,
    lng: -95.535,
    active: true,
  },
  {
    id: 'gsx-1',
    slug: 'west-side-gas-co',
    name: "West Side Gas Co",
    notes: "QuickBooks legal/source name: 1500 West Gentry (West Side Gas Co)",
    address: "1500 W. Gentry Ave",
    city: "Checotah",
    state: 'OK',
    zip: '74426',
    lat: 35.4358,
    lng: -95.535,
    active: true,
  },
  {
    id: 'gsx-98',
    slug: 'native-medicine-ltd-chelsea',
    name: "Native Medicine Ltd (Chelsea)",
    address: "219 E. Layton St",
    city: "Chelsea",
    state: 'OK',
    zip: '74016',
    lat: 36.5356,
    lng: -95.4489,
    active: true,
  },
  {
    id: 'gsx-6',
    slug: '405-gas-station-2-choctaw',
    name: "405 Gas Station 2 (Choctaw)",
    address: "14022 SE 29th St",
    city: "Choctaw",
    state: 'OK',
    zip: '73020',
    lat: 35.4718,
    lng: -97.2726,
    active: true,
  },
  {
    id: 'gsx-101',
    slug: 'nature-s-fix',
    name: "Nature's Fix",
    address: "210 S. Chouteau Ave",
    city: "Chouteau",
    state: 'OK',
    zip: '74337',
    lat: 36.1669,
    lng: -95.3416,
    active: true,
  },
  {
    id: 'gsx-11',
    slug: 'affordable-medical-inc-claremore',
    name: "Affordable Medical Inc Claremore",
    address: "321 S. Lynn Riggs Blvd",
    city: "Claremore",
    state: 'OK',
    zip: '74017',
    lat: 36.3242,
    lng: -95.5985,
    active: true,
  },
  {
    id: 'gsx-60',
    slug: 'green-canopy-solutions-inc',
    name: "Green Canopy Solutions, Inc.",
    address: "581 N. Lynn Riggs Blvd",
    city: "Claremore",
    state: 'OK',
    zip: '74017',
    lat: 36.3242,
    lng: -95.5985,
    active: true,
  },
  {
    id: 'gsx-112',
    slug: 'okies-high-hopes-inc',
    name: "Okies High Hopes Inc",
    address: "20105 E. Highway 20",
    city: "Claremore",
    state: 'OK',
    zip: '74019',
    lat: 36.2806,
    lng: -95.6039,
    active: true,
  },
  {
    id: 'gsx-156',
    slug: 'woodzeez-rt-66-weed-llc',
    name: "Woodzeez Rt 66 Weed LLC",
    address: "15805 S. Highway 66",
    city: "Claremore",
    state: 'OK',
    zip: '74017',
    lat: 36.3242,
    lng: -95.5985,
    active: true,
  },
  {
    id: 'gsx-14',
    slug: 'american-dispensary-llp',
    name: "American Dispensary LLP",
    address: "706 W. Caddo St",
    city: "Cleveland",
    state: 'OK',
    zip: '74020',
    lat: 36.2553,
    lng: -96.423,
    active: true,
  },
  {
    id: 'gsx-119',
    slug: 'redbilly-dispensary-1-llc',
    name: "Redbilly Dispensary 1, LLC",
    address: "3144 Highway 412",
    city: "Colcord",
    state: 'OK',
    zip: '74338',
    lat: 36.2333,
    lng: -94.6547,
    active: true,
  },
  {
    id: 'gsx-50',
    slug: 'flower-tops-llc-coweta',
    name: "Flower Tops LLC (Coweta)",
    address: "11150 S. 265th E. Ave.",
    city: "Coweta",
    state: 'OK',
    zip: '74429',
    lat: 35.9578,
    lng: -95.6526,
    active: true,
  },
  {
    id: 'gsx-117',
    slug: 'raw-wellness',
    name: "Raw Wellness",
    address: "804 E. Main St.",
    city: "Cushing",
    state: 'OK',
    zip: '74023',
    lat: 35.9822,
    lng: -96.7526,
    active: true,
  },
  {
    id: 'gsx-73',
    slug: 'humboldt-cannabis-dewey',
    name: "Humboldt Cannabis - Dewey",
    address: "316 S. Osage Ave",
    city: "Dewey",
    state: 'OK',
    zip: '74029',
    lat: 36.8013,
    lng: -95.9345,
    active: true,
  },
  {
    id: 'gsx-148',
    slug: 'urban-trichome-humboldt-dewey',
    name: "Urban Trichome (Humboldt Dewey)",
    address: "610 N. Osage Ave",
    city: "Dewey",
    state: 'OK',
    zip: '74029',
    lat: 36.8013,
    lng: -95.9345,
    active: true,
  },
  {
    id: 'gsx-16',
    slug: 'bodega-durant',
    name: "Bodega Durant",
    notes: "QuickBooks legal/source name: B&B Alternative (Bodega Durant)",
    address: "523 W. Main St.",
    city: "Durant",
    state: 'OK',
    zip: '74701',
    lat: 34.0061,
    lng: -96.3847,
    active: true,
  },
  {
    id: 'gsx-25',
    slug: 'bud-barn-wendell-michael-murphee',
    name: "Bud Barn - Wendell Michael Murphee",
    address: "624 W. Main St.",
    city: "Durant",
    state: 'OK',
    zip: '74701',
    lat: 34.0061,
    lng: -96.3847,
    active: true,
  },
  {
    id: 'gsx-86',
    slug: 'livwell-meds-of-calera-durant',
    name: "LivWell Meds of Calera (Durant)",
    address: "2813 W. University Blvd",
    city: "Durant",
    state: 'OK',
    zip: '74701',
    lat: 34.0061,
    lng: -96.3847,
    active: true,
  },
  {
    id: 'gsx-89',
    slug: 'loud-grams-llc',
    name: "Loud Grams LLC",
    address: "124 West Cedar Street",
    city: "Durant",
    state: 'OK',
    zip: '74701',
    lat: 34.0061,
    lng: -96.3847,
    active: true,
  },
  {
    id: 'gsx-77',
    slug: 'humboltd-edmond-spicy-chicken',
    name: "Humboltd Edmond - Spicy Chicken",
    address: "3230 S. Boulevard",
    city: "Edmond",
    state: 'OK',
    zip: '73013',
    lat: 35.6215,
    lng: -97.4733,
    active: true,
  },
  {
    id: 'gsx-104',
    slug: 'nexleaf-dispensary-edmond',
    name: "NexLeaf Dispensary (Edmond)",
    address: "1310 S. Broadway",
    city: "Edmond",
    state: 'OK',
    zip: '73034',
    lat: 35.6665,
    lng: -97.4798,
    active: true,
  },
  {
    id: 'gsx-127',
    slug: 'spark-cannabis-co-elgin',
    name: "Spark Cannabis Co. (Elgin)",
    address: "7567 US Hwy 277",
    city: "Elgin",
    state: 'OK',
    zip: '73538',
    lat: 34.772,
    lng: -98.4073,
    active: true,
  },
  {
    id: 'gsx-88',
    slug: 'health-express',
    name: "Health Express",
    notes: "QuickBooks legal/source name: Lotus Gold Enid (Health Express)",
    address: "5515 W. Owen K Garriott Rd",
    city: "Enid",
    state: 'OK',
    zip: '73703',
    lat: 36.3975,
    lng: -97.9157,
    active: true,
  },
  {
    id: 'gsx-34',
    slug: 'dank-banq-llc-glenpool',
    name: "Dank Banq LLC (Glenpool)",
    address: "13813 S. Casper St.",
    city: "Glenpool",
    state: 'OK',
    zip: '74033',
    lat: 35.9591,
    lng: -95.9997,
    active: true,
  },
  {
    id: 'gsx-27',
    slug: 'lemon',
    name: "Lemon",
    notes: "QuickBooks legal/source name: Canna-Cabana LLC (Lemon)",
    address: "12152 S. Waco Ave",
    city: "Glenpool",
    state: 'OK',
    zip: '74033',
    lat: 35.9591,
    lng: -95.9997,
    active: true,
  },
  {
    id: 'gsx-10',
    slug: '420releaf-llc',
    name: "420Releaf LLC",
    address: "21 W. 3rd St",
    city: "Grove",
    state: 'OK',
    zip: '74344',
    lat: 36.5929,
    lng: -94.7565,
    active: true,
  },
  {
    id: 'gsx-32',
    slug: 'corporation-asset-network-association-llc',
    name: "Corporation Asset Network Association LLC",
    address: "1620 S. Main St  #E",
    city: "Grove",
    state: 'OK',
    zip: '74344',
    lat: 36.5929,
    lng: -94.7565,
    active: true,
  },
  {
    id: 'gsx-59',
    slug: 'grand-lake-cannabis',
    name: "Grand Lake Cannabis",
    address: "520 W. 3rd St.",
    city: "Grove",
    state: 'OK',
    zip: '74344',
    lat: 36.5929,
    lng: -94.7565,
    active: true,
  },
  {
    id: 'gsx-58',
    slug: 'grand-s-golden-canna',
    name: "Grand's Golden Canna",
    address: "4621 US Hwy 59",
    city: "Grove",
    state: 'OK',
    zip: '74344',
    lat: 36.5929,
    lng: -94.7565,
    active: true,
  },
  {
    id: 'gsx-61',
    slug: 'green-culture-grove',
    name: "Green Culture (Grove)",
    address: "655 Rd",
    city: "Grove",
    state: 'OK',
    zip: '74344',
    lat: 36.5929,
    lng: -94.7565,
    active: true,
  },
  {
    id: 'gsx-87',
    slug: 'lokis-leaf-2',
    name: "Lokis Leaf 2",
    address: "619 S. Main St.",
    city: "Grove",
    state: 'OK',
    zip: '74344',
    lat: 36.5929,
    lng: -94.7565,
    active: true,
  },
  {
    id: 'gsx-7',
    slug: '405-gas-station-3-harrah',
    name: "405 Gas Station 3 (Harrah)",
    address: "3360 S. Harrah Rd",
    city: "Harrah",
    state: 'OK',
    zip: '73045',
    lat: 35.4833,
    lng: -97.1734,
    active: true,
  },
  {
    id: 'gsx-39',
    slug: 'dazey-s-hartshorne',
    name: "Dazey's - Hartshorne",
    address: "103 N. 11th St",
    city: "Hartshorne",
    state: 'OK',
    zip: '74547',
    lat: 34.8452,
    lng: -95.574,
    active: true,
  },
  {
    id: 'gsx-142',
    slug: 'grow-cannabis',
    name: "Grow Cannabis",
    notes: "QuickBooks legal/source name: Top Hat Dispo (Grow Cannabis)",
    address: "2005 St. Hwy 99",
    city: "Hominy",
    state: 'OK',
    zip: '74035',
    lat: 36.4111,
    lng: -96.3878,
    active: true,
  },
  {
    id: 'gsx-135',
    slug: 'the-back-house-llc',
    name: "The Back House LLC",
    address: "113 W. Main St",
    city: "Hominy",
    state: 'OK',
    zip: '74035',
    lat: 36.4111,
    lng: -96.3878,
    active: true,
  },
  {
    id: 'gsx-154',
    slug: 'wholesale-cannabis-jay',
    name: "Wholesale Cannabis (Jay)",
    address: "272 S. 5th St",
    city: "Jay",
    state: 'OK',
    zip: '74346',
    lat: 36.4363,
    lng: -94.7763,
    active: true,
  },
  {
    id: 'gsx-30',
    slug: 'cannabis-31',
    name: "Cannabis 31",
    notes: "QuickBooks legal/source name: Christopher Woodall (Canabis 31)",
    address: "1200 W. Washington",
    city: "Krebs",
    state: 'OK',
    zip: '74554',
    lat: 34.9255,
    lng: -95.7216,
    active: true,
  },
  {
    id: 'gsx-41',
    slug: 'dazey-s-cannabis-company',
    name: "Dazey's Cannabis Company",
    address: "64 S. McFarland St",
    city: "Krebs",
    state: 'OK',
    zip: '74554',
    lat: 34.9255,
    lng: -95.7216,
    active: true,
  },
  {
    id: 'gsx-81',
    slug: 'big-chief-lawton',
    name: "Big Chief Lawton",
    notes: "QuickBooks legal/source name: Joseph Wario-Garcia (Big Chief Lawton)",
    address: "3414 NW Cache Rd",
    city: "Lawton",
    state: 'OK',
    zip: '73505',
    lat: 34.6179,
    lng: -98.4552,
    active: true,
  },
  {
    id: 'gsx-52',
    slug: 'g2g-dispensary-llc-big-chief-2',
    name: "G2G Dispensary LLC(Big Chief #2)",
    address: "329 SW C Avenue",
    city: "Lawton",
    state: 'OK',
    zip: '73501',
    lat: 34.5915,
    lng: -98.3698,
    active: true,
  },
  {
    id: 'gsx-122',
    slug: 'shake-shack',
    name: "Shake Shack",
    address: "8907 NW Cache Rd",
    city: "Lawton",
    state: 'OK',
    zip: '73505',
    lat: 34.6179,
    lng: -98.4552,
    active: true,
  },
  {
    id: 'gsx-128',
    slug: 'spark-cannabis-co-lawton',
    name: "Spark Cannabis Co. (Lawton)",
    address: "2619 NW Cache Road",
    city: "Lawton",
    state: 'OK',
    zip: '73505',
    lat: 34.6179,
    lng: -98.4552,
    active: true,
  },
  {
    id: 'gsx-138',
    slug: 'the-purple-dragon-dispensary',
    name: "The Purple Dragon Dispensary",
    address: "1314 W. Gore Blvd",
    city: "Lawton",
    state: 'OK',
    zip: '73501',
    lat: 34.5915,
    lng: -98.3698,
    active: true,
  },
  {
    id: 'gsx-84',
    slug: 'keystone-alternative-medicine-llp',
    name: "Keystone Alternative Medicine LLP",
    address: "103 Phelps Ave",
    city: "Mannford",
    state: 'OK',
    zip: '74044',
    lat: 36.0927,
    lng: -96.3576,
    active: true,
  },
  {
    id: 'gsx-42',
    slug: 'chillin-station',
    name: "Chillin Station",
    notes: "QuickBooks legal/source name: DE & SE Inc (Chillin Station)",
    address: "2009 N. Main St",
    city: "McAlester",
    state: 'OK',
    zip: '74501',
    lat: 34.9262,
    lng: -95.7592,
    active: true,
  },
  {
    id: 'gsx-40',
    slug: 'dazey-s-cannabis-mcalester',
    name: "Dazey's Cannabis - McAlester",
    address: "414 W. Carl Albert Parkway",
    city: "McAlester",
    state: 'OK',
    zip: '74501',
    lat: 34.9262,
    lng: -95.7592,
    active: true,
  },
  {
    id: 'gsx-53',
    slug: 'ganja-shack-inc',
    name: "Ganja Shack Inc.",
    address: "800 N. Main St",
    city: "McAlester",
    state: 'OK',
    zip: '74501',
    lat: 34.9262,
    lng: -95.7592,
    active: true,
  },
  {
    id: 'gsx-113',
    slug: 'oklahoma-kush-cannabis-co-3',
    name: "Oklahoma Kush Cannabis Co #3",
    notes: "QuickBooks legal/source name: Oklahoma Kush Cannabis Co #3 (McAlester). Same address also billed under a second customer record (\"Bodgea McAlester - OK Kush Cannabis #3\") — merged to one listing.",
    address: "222 E. Choctaw Ave",
    city: "McAlester",
    state: 'OK',
    zip: '74501',
    lat: 34.9262,
    lng: -95.7592,
    active: true,
  },
  {
    id: 'gsx-23',
    slug: 'bodega-boyz-of-miami',
    name: "Bodega Boyz of Miami",
    address: "502 Henley St",
    city: "Miami",
    state: 'OK',
    zip: '74354',
    lat: 36.8764,
    lng: -94.8719,
    active: true,
  },
  {
    id: 'gsx-51',
    slug: 'fritz-fire-house-miami-ok-llc',
    name: "Fritz Fire House Miami OK LLC",
    address: "101 W. Steve Owens Blvd",
    city: "Miami",
    state: 'OK',
    zip: '74354',
    lat: 36.8764,
    lng: -94.8719,
    active: true,
  },
  {
    id: 'gsx-62',
    slug: 'green-culture-llc',
    name: "Green Culture LLC",
    address: "1429 E. Steve Owens Blvd",
    city: "Miami",
    state: 'OK',
    zip: '74354',
    lat: 36.8764,
    lng: -94.8719,
    active: true,
  },
  {
    id: 'gsx-74',
    slug: 'humboldt-cannabis-miami',
    name: "Humboldt Cannabis - Miami",
    address: "1101 E. Steve Owens Blvd",
    city: "Miami",
    state: 'OK',
    zip: '74354',
    lat: 36.8764,
    lng: -94.8719,
    active: true,
  },
  {
    id: 'gsx-93',
    slug: 'mits-farmacy',
    name: "MiTs Farmacy",
    address: "102 A St NE",
    city: "Miami",
    state: 'OK',
    zip: '74354',
    lat: 36.8764,
    lng: -94.8719,
    active: true,
  },
  {
    id: 'gsx-5',
    slug: '405-gas-station-1-mwc',
    name: "405 Gas Station 1 (MWC)",
    address: "9401 E. Reno",
    city: "Midwest City",
    state: 'OK',
    zip: '73130',
    lat: 35.4604,
    lng: -97.3419,
    active: true,
  },
  {
    id: 'gsx-29',
    slug: 'chasing-wolves-gas-station-mwc',
    name: "Chasing Wolves (Gas Station MWC)",
    address: "9401 E. Reno Ave.",
    city: "Midwest City",
    state: 'OK',
    zip: '73130',
    lat: 35.4604,
    lng: -97.3419,
    active: true,
  },
  {
    id: 'gsx-31',
    slug: 'green-cloud-mwc',
    name: "Green Cloud MWC",
    notes: "QuickBooks legal/source name: Cloud Enterprise (Green Cloud MWC)",
    address: "218 S. Sooner Rd",
    city: "Midwest City",
    state: 'OK',
    zip: '73110',
    lat: 35.4605,
    lng: -97.3974,
    active: true,
  },
  {
    id: 'gsx-103',
    slug: 'neok-pain-relief-llc',
    name: "NEOK Pain Relief LLC",
    address: "3143 Azalea Park Dr",
    city: "Muskogee",
    state: 'OK',
    zip: '74401',
    lat: 35.7058,
    lng: -95.5002,
    active: true,
  },
  {
    id: 'gsx-102',
    slug: 'ouncehouse',
    name: "Ouncehouse",
    notes: "QuickBooks legal/source name: Navigator Life Services Inc. (Ouncehouse)",
    address: "717 W. Broadway St",
    city: "Muskogee",
    state: 'OK',
    zip: '74401',
    lat: 35.7058,
    lng: -95.5002,
    active: true,
  },
  {
    id: 'gsx-139',
    slug: 'the-vault-by-grow-happy-farms-llc',
    name: "The Vault by Grow Happy Farms LLC",
    address: "832 N. Main St",
    city: "Muskogee",
    state: 'OK',
    zip: '74401',
    lat: 35.7058,
    lng: -95.5002,
    active: true,
  },
  {
    id: 'gsx-37',
    slug: 'david-s-cloud-llc',
    name: "David's Cloud LLC",
    address: "9001 S. Harrah Rd",
    city: "Newalla",
    state: 'OK',
    zip: '74857',
    lat: 35.3734,
    lng: -97.1971,
    active: true,
  },
  {
    id: 'gsx-78',
    slug: 'in-the-weeds-llc',
    name: "In the Weeds LLC",
    address: "2315 E. Lindsey St",
    city: "Norman",
    state: 'OK',
    zip: '73071',
    lat: 35.233,
    lng: -97.4067,
    active: true,
  },
  {
    id: 'gsx-96',
    slug: 'mr-green-riverwind-norman',
    name: "Mr. Green Riverwind (Norman)",
    address: "1960 W. St Hwy 9",
    city: "Norman",
    state: 'OK',
    zip: '73072',
    lat: 35.199,
    lng: -97.4841,
    active: true,
  },
  {
    id: 'gsx-108',
    slug: 'noble-cannabis-co-dispensary',
    name: "Noble Cannabis Co. Dispensary",
    address: "2202 Tecumseh Dr",
    city: "Norman",
    state: 'OK',
    zip: '73069',
    lat: 35.2204,
    lng: -97.4577,
    active: true,
  },
  {
    id: 'gsx-143',
    slug: 'trifecta-farms-llc',
    name: "Trifecta Farms LLC",
    address: "3420 N. Porter Ave",
    city: "Norman",
    state: 'OK',
    zip: '73071',
    lat: 35.233,
    lng: -97.4067,
    active: true,
  },
  {
    id: 'gsx-150',
    slug: 'vertica-dispensary-norman',
    name: "Vertica Dispensary - Norman",
    address: "1729 W. Main St.",
    city: "Norman",
    state: 'OK',
    zip: '73069',
    lat: 35.2204,
    lng: -97.4577,
    active: true,
  },
  {
    id: 'gsx-99',
    slug: 'native-medicine-ltd-nowata',
    name: "Native Medicine Ltd (Nowata)",
    address: "117 E. Cherokee Ave",
    city: "Nowata",
    state: 'OK',
    zip: '74048',
    lat: 36.6946,
    lng: -95.6404,
    active: true,
  },
  {
    id: 'gsx-33',
    slug: 'dana-s-green-depot',
    name: "Dana's Green Depot",
    address: "5801 W. Britton Rd",
    city: "Oklahoma City",
    state: 'OK',
    zip: '73132',
    lat: 35.5583,
    lng: -97.6375,
    active: true,
  },
  {
    id: 'gsx-83',
    slug: 'farmacy-okc',
    name: "Farmacy OKC",
    notes: "QuickBooks legal/source name: KD Ventures (Farmacy OKC)",
    address: "4208 SW 149th St",
    city: "Oklahoma City",
    state: 'OK',
    zip: '73170',
    lat: 35.327,
    lng: -97.5556,
    active: true,
  },
  {
    id: 'gsx-49',
    slug: 'flower-leaf-llc',
    name: "Flower & Leaf LLC",
    address: "12325 N. May Ave.",
    city: "Oklahoma City",
    state: 'OK',
    zip: '73120',
    lat: 35.5835,
    lng: -97.5638,
    active: true,
  },
  {
    id: 'gsx-65',
    slug: 'green-lily-llc',
    name: "Green Lily LLC",
    address: "4301 N. Sara Road",
    city: "Oklahoma City",
    state: 'OK',
    zip: '73099',
    lat: 35.4977,
    lng: -97.7323,
    active: true,
  },
  {
    id: 'gsx-79',
    slug: 'indica-cannabis-co-okc',
    name: "Indica Cannabis Co.(OKC)",
    address: "12404 N. Macarthur Blvd",
    city: "Oklahoma City",
    state: 'OK',
    zip: '73142',
    lat: 35.599,
    lng: -97.6251,
    active: true,
  },
  {
    id: 'gsx-105',
    slug: 'nexleaf-dispensary-okc-23rd-st',
    name: "NexLeaf Dispensary (OKC 23rd St)",
    address: "9113 NE 23rd St",
    city: "Oklahoma City",
    state: 'OK',
    zip: '73141',
    lat: 35.4918,
    lng: -97.3666,
    active: true,
  },
  {
    id: 'gsx-106',
    slug: 'nexleaf-dispensary-okc-council-rd',
    name: "NexLeaf Dispensary (OKC Council Rd)",
    address: "11 S. Council Rd",
    city: "Oklahoma City",
    state: 'OK',
    zip: '73127',
    lat: 35.4834,
    lng: -97.6299,
    active: true,
  },
  {
    id: 'gsx-107',
    slug: 'nexleaf-dispensary-okc-penn',
    name: "NexLeaf Dispensary (OKC Penn)",
    address: "7515 S Penn Ave",
    city: "Oklahoma City",
    state: 'OK',
    zip: '73159',
    lat: 35.3922,
    lng: -97.5567,
    active: true,
  },
  {
    id: 'gsx-121',
    slug: 'project-releaf',
    name: "Project Releaf",
    notes: "QuickBooks legal/source name: Roots Distribution (Project Releaf)",
    address: "1218 N. Pennsylvania Ave",
    city: "Oklahoma City",
    state: 'OK',
    zip: '73107',
    lat: 35.4874,
    lng: -97.574,
    active: true,
  },
  {
    id: 'gsx-126',
    slug: 'eden-cannabis',
    name: "Eden Cannabis",
    notes: "QuickBooks legal/source name: Sommet Ventures Inc (Eden Cannabis)",
    address: "1731 E. 6th St",
    city: "Okmulgee",
    state: 'OK',
    zip: '74447',
    lat: 35.6288,
    lng: -95.9697,
    active: true,
  },
  {
    id: 'gsx-46',
    slug: 'evermore-cannabis-dispensary-okmulgee',
    name: "Evermore Cannabis Dispensary (Okmulgee)",
    address: "814 S. Wood Dr.",
    city: "Okmulgee",
    state: 'OK',
    zip: '74447',
    lat: 35.6288,
    lng: -95.9697,
    active: true,
  },
  {
    id: 'gsx-36',
    slug: 'dark-cloud-cannabis-llc-oologah',
    name: "Dark Cloud Cannabis LLC (Oologah)",
    address: "365 S. Hwy 169",
    city: "Oologah",
    state: 'OK',
    zip: '74053',
    lat: 36.4482,
    lng: -95.7047,
    active: true,
  },
  {
    id: 'gsx-35',
    slug: 'dank-banq-llc-owasso',
    name: "Dank Banq LLC (Owasso)",
    address: "8571 N. Owasso Expy Unit A-2",
    city: "Owasso",
    state: 'OK',
    zip: '74055',
    lat: 36.2863,
    lng: -95.8222,
    active: true,
  },
  {
    id: 'gsx-47',
    slug: 'evermore-exotics-owasso',
    name: "Evermore Exotics (Owasso)",
    address: "7800 N. Owasso Expy STE A",
    city: "Owasso",
    state: 'OK',
    zip: '74055',
    lat: 36.2863,
    lng: -95.8222,
    active: true,
  },
  {
    id: 'gsx-75',
    slug: 'humboldt-cannabis-owasso',
    name: "Humboldt Cannabis - Owasso",
    notes: "QuickBooks legal/source name: Humboldt Cannabis - Owasso. Same address also billed under a second customer record (\"Humboldt Owasso(Emerald Bison)\") — merged to one listing.",
    address: "422 E. 22nd St.",
    city: "Owasso",
    state: 'OK',
    zip: '74055',
    lat: 36.2863,
    lng: -95.8222,
    active: true,
  },
  {
    id: 'gsx-12',
    slug: 'affordable-medical-inc-pryor',
    name: "Affordable Medical Inc Pryor",
    address: "102 NE 1st St",
    city: "Pryor",
    state: 'OK',
    zip: '74361',
    lat: 36.2921,
    lng: -95.3129,
    active: true,
  },
  {
    id: 'gsx-129',
    slug: 'stoney-s-joint-pryor-llc',
    name: "Stoney's Joint Pryor LLC",
    address: "202 S. Adair St.",
    city: "Pryor Creek",
    state: 'OK',
    zip: '74361',
    lat: 36.2921,
    lng: -95.3129,
    active: true,
  },
  {
    id: 'gsx-64',
    slug: 'moodz-purcell',
    name: "Moodz Purcell",
    notes: "QuickBooks legal/source name: Green Leaf Cannabis (Moodz Purcell)",
    address: "1736 S. Green Ave.",
    city: "Purcell",
    state: 'OK',
    zip: '73080',
    lat: 35.0103,
    lng: -97.4255,
    active: true,
  },
  {
    id: 'gsx-97',
    slug: 'nanas-joint-llc-salina',
    name: "Nanas Joint LLC (Salina)",
    address: "209 W. Ferry St.",
    city: "Salina",
    state: 'OK',
    zip: '74365',
    lat: 36.3116,
    lng: -95.1158,
    active: true,
  },
  {
    id: 'gsx-151',
    slug: 'cannabis-marketplace',
    name: "Cannabis Marketplace",
    notes: "QuickBooks legal/source name: Vertical Horizon (Cannabis Marketplace)",
    address: "430 W. Wekiwa Rd",
    city: "Sand Springs",
    state: 'OK',
    zip: '74063',
    lat: 36.1341,
    lng: -96.1426,
    active: true,
  },
  {
    id: 'gsx-95',
    slug: 'herbal-joint',
    name: "Herbal Joint",
    notes: "QuickBooks legal/source name: Molly Asset Management (Herbal Joint)",
    address: "3417 S. 113th West Ave",
    city: "Sand Springs",
    state: 'OK',
    zip: '74063',
    lat: 36.1341,
    lng: -96.1426,
    active: true,
  },
  {
    id: 'gsx-69',
    slug: 'hillbilly-gas',
    name: "Hillbilly Gas",
    address: "17628 W 8th St",
    city: "Sand Springs",
    state: 'OK',
    zip: '74063',
    lat: 36.1341,
    lng: -96.1426,
    active: true,
  },
  {
    id: 'gsx-109',
    slug: 'ohg-llc-ss-41st-st',
    name: "OHG, LLC - SS 41st St",
    address: "3 E. 41st St Suite B",
    city: "Sand Springs",
    state: 'OK',
    zip: '74063',
    lat: 36.1341,
    lng: -96.1426,
    active: true,
  },
  {
    id: 'gsx-110',
    slug: 'ohg-llc-ss-8th-st',
    name: "OHG, LLC - SS 8th St.",
    address: "20915 W. 8th St. S.",
    city: "Sand Springs",
    state: 'OK',
    zip: '74063',
    lat: 36.1341,
    lng: -96.1426,
    active: true,
  },
  {
    id: 'gsx-153',
    slug: 'westside-wellness-llc',
    name: "Westside Wellness LLC",
    address: "1138 E. Charles Page Blvd",
    city: "Sand Springs",
    state: 'OK',
    zip: '74063',
    lat: 36.1341,
    lng: -96.1426,
    active: true,
  },
  {
    id: 'gsx-136',
    slug: 'earth-wind-flower',
    name: "Earth Wind & Flower",
    notes: "QuickBooks legal/source name: The Baked Bean (Earth Wind & Flower)",
    address: "724 S. Mission St.",
    city: "Sapulpa",
    state: 'OK',
    zip: '74066',
    lat: 36.003,
    lng: -96.1106,
    active: true,
  },
  {
    id: 'gsx-26',
    slug: 'm-m-connection',
    name: "M&M Connection",
    notes: "QuickBooks legal/source name: Cabin Creek Holdings LLC (M&M Connection)",
    address: "1206 N. Mission St.",
    city: "Sapulpa",
    state: 'OK',
    zip: '74066',
    lat: 36.003,
    lng: -96.1106,
    active: true,
  },
  {
    id: 'gsx-116',
    slug: 'purple-moon-dispensary-inc',
    name: "Purple Moon Dispensary Inc.",
    address: "821 E. Dewey Ave",
    city: "Sapulpa",
    state: 'OK',
    zip: '74066',
    lat: 36.003,
    lng: -96.1106,
    active: true,
  },
  {
    id: 'gsx-149',
    slug: 'vaporherbs-llc',
    name: "VaporHerbs LLC",
    address: "802 W. Taft Ave",
    city: "Sapulpa",
    state: 'OK',
    zip: '74066',
    lat: 36.003,
    lng: -96.1106,
    active: true,
  },
  {
    id: 'gsx-152',
    slug: 'vhe-dispensary',
    name: "VHE Dispensary",
    address: "1104 E. Taft Ave",
    city: "Sapulpa",
    state: 'OK',
    zip: '74066',
    lat: 36.003,
    lng: -96.1106,
    active: true,
  },
  {
    id: 'gsx-155',
    slug: 'wholesale-cannabis-sapulpa',
    name: "Wholesale Cannabis (Sapulpa)",
    address: "805 E. Hobson Ave",
    city: "Sapulpa",
    state: 'OK',
    zip: '74066',
    lat: 36.003,
    lng: -96.1106,
    active: true,
  },
  {
    id: 'gsx-133',
    slug: 'tanks-dank-llc',
    name: "Tanks Dank LLC",
    address: "210 E. W Rogers Bldv",
    city: "Skiatook",
    state: 'OK',
    zip: '74070',
    lat: 36.3725,
    lng: -96.0123,
    active: true,
  },
  {
    id: 'gsx-141',
    slug: 'toke-and-grow-skiatook',
    name: "Toke and Grow - Skiatook",
    address: "415 W. Rogers Blvd",
    city: "Skiatook",
    state: 'OK',
    zip: '74070',
    lat: 36.3725,
    lng: -96.0123,
    active: true,
  },
  {
    id: 'gsx-56',
    slug: 'cannacure',
    name: "CannaCure",
    notes: "QuickBooks legal/source name: Glow Ventures (CannaCure)",
    address: "1023 E. 6th Ave",
    city: "Stillwater",
    state: 'OK',
    zip: '74074',
    lat: 36.1043,
    lng: -97.0609,
    active: true,
  },
  {
    id: 'gsx-100',
    slug: 'natural-healing-remedies-llc',
    name: "Natural Healing Remedies LLC",
    address: "211 N. Perkins Rd #36",
    city: "Stillwater",
    state: 'OK',
    zip: '74075',
    lat: 36.1396,
    lng: -97.063,
    active: true,
  },
  {
    id: 'gsx-131',
    slug: 'stroud-dispensary-llc',
    name: "Stroud Dispensary LLC",
    address: "411 W. Main St",
    city: "Stroud",
    state: 'OK',
    zip: '74079',
    lat: 35.7398,
    lng: -96.6719,
    active: true,
  },
  {
    id: 'gsx-120',
    slug: 'right-time-medical-llc',
    name: "Right Time Medical LLC",
    address: "3040 S. Muskogee Ave #106",
    city: "Tahlequah",
    state: 'OK',
    zip: '74464',
    lat: 35.9094,
    lng: -94.9787,
    active: true,
  },
  {
    id: 'gsx-130',
    slug: 'stoney-s-joint-tahlequah',
    name: "Stoney's Joint Tahlequah",
    address: "1401 1/2 E. Downing St.",
    city: "Tahlequah",
    state: 'OK',
    zip: '74464',
    lat: 35.9094,
    lng: -94.9787,
    active: true,
  },
  {
    id: 'gsx-17',
    slug: 'best-dispensaries',
    name: "Best Dispensaries",
    address: "1502 S. Harvard Ave.",
    city: "Tulsa",
    state: 'OK',
    zip: '74112',
    lat: 36.147,
    lng: -95.907,
    active: true,
  },
  {
    id: 'gsx-123',
    slug: 'bodega-boyz',
    name: "Bodega Boyz",
    notes: "QuickBooks legal/source name: Simply Cultivation (Bodega Boyz)",
    address: "9749 E. 54th St.",
    city: "Tulsa",
    state: 'OK',
    zip: '74146',
    lat: 36.1093,
    lng: -95.8506,
    active: true,
  },
  {
    id: 'gsx-20',
    slug: 'bodega-boyz-61st',
    name: "Bodega Boyz 61st",
    address: "8316 E. 61st St",
    city: "Tulsa",
    state: 'OK',
    zip: '74133',
    lat: 36.0467,
    lng: -95.8841,
    active: true,
  },
  {
    id: 'gsx-21',
    slug: 'bodega-boyz-71st',
    name: "Bodega Boyz 71st",
    address: "7030 S. Sheridan Rd",
    city: "Tulsa",
    state: 'OK',
    zip: '74133',
    lat: 36.0467,
    lng: -95.8841,
    active: true,
  },
  {
    id: 'gsx-22',
    slug: 'bodega-boyz-91st',
    name: "Bodega Boyz 91st",
    address: "7717 E. 91st St.",
    city: "Tulsa",
    state: 'OK',
    zip: '74133',
    lat: 36.0467,
    lng: -95.8841,
    active: true,
  },
  {
    id: 'gsx-124',
    slug: 'bodega-lewis',
    name: "Bodega Lewis",
    notes: "QuickBooks legal/source name: Simply Toke (Bodega Lewis)",
    address: "1548 N. Lewis Ave",
    city: "Tulsa",
    state: 'OK',
    zip: '74110',
    lat: 36.1803,
    lng: -95.9525,
    active: true,
  },
  {
    id: 'gsx-28',
    slug: 'canna-shack-tulsa',
    name: "Canna Shack (Tulsa)",
    address: "2730 S. Harvard Ave.",
    city: "Tulsa",
    state: 'OK',
    zip: '74114',
    lat: 36.1262,
    lng: -95.9408,
    active: true,
  },
  {
    id: 'gsx-48',
    slug: 'flavor-chasers',
    name: "Flavor Chasers",
    address: "2036 E. 81st St",
    city: "Tulsa",
    state: 'OK',
    zip: '74137',
    lat: 36.0284,
    lng: -95.9306,
    active: true,
  },
  {
    id: 'gsx-125',
    slug: 'golden-circle',
    name: "Golden Circle",
    notes: "QuickBooks legal/source name: SK Affiliates (Golden Circle)",
    address: "4538 N. Martin Luther King Jr Blvd",
    city: "Tulsa",
    state: 'OK',
    zip: '74106',
    lat: 36.1883,
    lng: -95.986,
    active: true,
  },
  {
    id: 'gsx-57',
    slug: 'good-greens-dispensary-inc',
    name: "Good Greens Dispensary Inc",
    address: "1333 N. Utica Ave",
    city: "Tulsa",
    state: 'OK',
    zip: '74110',
    lat: 36.1803,
    lng: -95.9525,
    active: true,
  },
  {
    id: 'gsx-132',
    slug: 'hazey-hideaway',
    name: "Hazey Hideaway",
    notes: "QuickBooks legal/source name: Sweet Leaf Endeavors (Hazey Hideaway)",
    address: "1535 N. 107th E. Ave",
    city: "Tulsa",
    state: 'OK',
    zip: '74116',
    lat: 36.175,
    lng: -95.8477,
    active: true,
  },
  {
    id: 'gsx-67',
    slug: 'herbal-meds-llc',
    name: "Herbal Meds LLC",
    address: "3018 E. Pine St.",
    city: "Tulsa",
    state: 'OK',
    zip: '74110',
    lat: 36.1803,
    lng: -95.9525,
    active: true,
  },
  {
    id: 'gsx-82',
    slug: 'jive',
    name: "Jive",
    notes: "QuickBooks legal/source name: Just Another Bowl Inc (Jive)",
    address: "10922 S. Memorial Drive",
    city: "Tulsa",
    state: 'OK',
    zip: '74133',
    lat: 36.0467,
    lng: -95.8841,
    active: true,
  },
  {
    id: 'gsx-54',
    slug: 'lovelight',
    name: "Lovelight",
    notes: "QuickBooks legal/source name: GDTRFB Holdings (Lovelight)",
    address: "3618 E Admiral Pl",
    city: "Tulsa",
    state: 'OK',
    zip: '74115',
    lat: 36.1754,
    lng: -95.9112,
    active: true,
  },
  {
    id: 'gsx-94',
    slug: 'mary-jane-s',
    name: "Mary Jane's",
    notes: "QuickBooks legal/source name: Moesha Maxwell (Mary Jane's)",
    address: "2030 E Pine St",
    city: "Tulsa",
    state: 'OK',
    zip: '74110',
    lat: 36.1803,
    lng: -95.9525,
    active: true,
  },
  {
    id: 'gsx-111',
    slug: 'ohg-llc-tulsa',
    name: "OHG, LLC - Tulsa",
    address: "9954 E. 21st St",
    city: "Tulsa",
    state: 'OK',
    zip: '74129',
    lat: 36.1259,
    lng: -95.8654,
    active: true,
  },
  {
    id: 'gsx-118',
    slug: 'real-green-dispensary-tulsa',
    name: "Real Green Dispensary (Tulsa)",
    address: "418 S. Memorial Dr",
    city: "Tulsa",
    state: 'OK',
    zip: '74112',
    lat: 36.147,
    lng: -95.907,
    active: true,
  },
  {
    id: 'gsx-145',
    slug: 't-town-medical',
    name: "T-Town Medical",
    notes: "QuickBooks legal/source name: Tulsa Tokes (T-Town Medical)",
    address: "3524 S. Sheridan Rd",
    city: "Tulsa",
    state: 'OK',
    zip: '74145',
    lat: 36.0934,
    lng: -95.8856,
    active: true,
  },
  {
    id: 'gsx-134',
    slug: 'taylor-oversee-inc-tulsa-dispensary',
    name: "Taylor Oversee Inc. (Tulsa Dispensary)",
    address: "5910 S. 107th E. Ave.",
    city: "Tulsa",
    state: 'OK',
    zip: '74146',
    lat: 36.1093,
    lng: -95.8506,
    active: true,
  },
  {
    id: 'gsx-146',
    slug: 'tulsa-tree-house-n-lewis',
    name: "Tulsa Tree House (N. Lewis)",
    address: "4604 N. Lewis Ave",
    city: "Tulsa",
    state: 'OK',
    zip: '74130',
    lat: 36.2395,
    lng: -95.9596,
    active: true,
  },
  {
    id: 'gsx-13',
    slug: 'alternacare-medical-cannabis-llc',
    name: "Alternacare Medical Cannabis LLC",
    address: "216 S 7th St   STE4",
    city: "Vinita",
    state: 'OK',
    zip: '74301',
    lat: 36.6334,
    lng: -95.1382,
    active: true,
  },
  {
    id: 'gsx-55',
    slug: 'giggling-bud-corporation',
    name: "Giggling Bud Corporation",
    address: "201 W. Cherokee St.",
    city: "Wagoner",
    state: 'OK',
    zip: '74467',
    lat: 35.9549,
    lng: -95.354,
    active: true,
  },
  {
    id: 'gsx-115',
    slug: 'purple-haze-weatherford',
    name: "Purple Haze (Weatherford)",
    address: "320 N. Washington Ave",
    city: "Weatherford",
    state: 'OK',
    zip: '73096',
    lat: 35.535,
    lng: -98.6996,
    active: true,
  },
  {
    id: 'gsx-68',
    slug: 'happy-harry-s',
    name: "Happy Harry's",
    notes: "QuickBooks legal/source name: HHMS (Happy Harry's)",
    address: "69708 E. Hwy 60",
    city: "Wyandotte",
    state: 'OK',
    zip: '74370',
    lat: 36.7796,
    lng: -94.7002,
    active: true,
  },
  {
    id: 'gsx-80',
    slug: 'okie-medicine-yukon',
    name: "Okie Medicine Yukon",
    notes: "QuickBooks legal/source name: Jameson & Sons (Okie Medicine Yukon)",
    address: "1701 S. Mustang Rd",
    city: "Yukon",
    state: 'OK',
    zip: '73099',
    lat: 35.4977,
    lng: -97.7323,
    active: true,
  },
]
